Otra vez

diff --git a/.github/workflows/maven_examen2gestiondelaconfiguracion.yml b/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
--- a/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
+++ b/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
@@ -22,11 +22,18 @@ jobs:
           java-version: '17'
 
       - name: Build with Maven
-        run: mvn clean install
+        run: |
+          # Este es un script que intencionalmente fallará el build
+          echo "Simulando un error en el build..."
+          exit 1
+        continue-on-error: true  # Continuar incluso si esta etapa falla
 
-  upload-artifacts:
+  deploy:
     runs-on: ubuntu-latest
     needs: build
+    environment:
+      name: 'Production'
+    
     steps:
       - name: Upload artifact for deployment
         uses: actions/upload-artifact@v2
@@ -34,13 +41,6 @@ jobs:
           name: java-app
           path: '${{ github.workspace }}/target/*.jar'
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: upload-artifacts
-    environment:
-      name: 'Production'
-    
-    steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v2
         with:
