veams

diff --git a/.github/workflows/maven_examen2gestiondelaconfiguracion.yml b/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
--- a/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
+++ b/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
@@ -1,9 +1,6 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy JAR app to Azure Web App - Examen2GestionDeLaConfiguracion
 
 on:
@@ -26,7 +23,10 @@ jobs:
 
       - name: Build with Maven
         run: mvn clean install
-        continue-on-error: true  # Continúa incluso si este paso falla
+
+      - name: Intentionally Fail Test
+        run: echo "Test failed" && exit 1
+        if: always()  # This step will always run and intentionally fail
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
@@ -55,12 +55,4 @@ jobs:
           slot-name: 'Production'
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EDC0C5C3034B4AE597ACE3F1DE4A5F69 }}
           package: '*.jar'
-
-# Esta acción se ejecutará siempre, incluso si el paso de construcción falla
-always-succeed:
-  runs-on: ubuntu-latest
-  needs: deploy
-  steps:
-    - name: Always succeed
-      run: echo "This step always succeeds"
 
