Aaaa

diff --git a/.github/workflows/maven_examen2gestiondelaconfiguracion.yml b/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
--- a/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
+++ b/.github/workflows/maven_examen2gestiondelaconfiguracion.yml
@@ -25,11 +25,12 @@ jobs:
           java-version: '17'
 
       - name: Build with Maven
-        run: |
-          # Insert a command here that intentionally fails the build, for example:
-          # exit 1
-          mvn clean install || exit 1  # This will fail the build but continue execution
-          
+        run: mvn clean install
+
+      - name: Intentionally Fail Test
+        run: echo "Test failed" && exit 1
+        if: always()  # This step will always run and intentionally fail
+
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
         with:
@@ -58,19 +59,5 @@ jobs:
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EDC0C5C3034B4AE597ACE3F1DE4A5F69 }}
           package: '*.jar'
 
-# This step intentionally fails but continues the workflow
-  fail-step:
-    runs-on: ubuntu-latest
-    needs: deploy
-    steps:
-      - name: Fail the workflow
-        run: exit 1
-
-# Mark the workflow as failed but continue executing the subsequent actions
-on:
-  workflow_run:
-    workflows: ["Build and deploy JAR app to Azure Web App - Examen2GestionDeLaConfiguracion"]
-    types:
-      - completed
 
 
